### ISSUE TITLE
"forms" is identical with value when adding it in lexibank

### ISSUE THREAD

**Issue by LinguList** [lexibank/marrisonnaga#12]
Is this a bug or a feature? Since I switched to "nonsplittingdataset", I can't pass a different "form" parameter. If you check the code in marrisonnaga here, you will see that the value and the form are both identical, although I explicitly add the splitted value (but only its first elements, as these are usually variants in stedt).

**Comment by xrotwang** [comment]
A feature. Form is created by pylexibank from value. So if you want to
explicitly control both, original value and the form, you'd have to add a
column orig_value or similar, pass what you want as form as value, and let
pylexibank do it's thing.

Am Mi., 20. Feb. 2019, 18:10 hat Johann-Mattis List <
notifications@github.com> geschrieben:

**Comment by LinguList** [comment]
Okay, this is straightforward, I just realize always that I will resort to non-standard solutions in those cases, where I don't know we already have solutions. 

How I fixed this now (to have my desired behavior), was to override the "clean_form":

```
    def clean_form(self, item, form):
        
        if form not in ['*', '---', '']:
            return form.split(',')[0]


```
