### ISSUE TITLE
make new orthoprofile from current data

### ISSUE THREAD

**Issue by LinguList** [lexibank/marrisonnaga#14]
```
$ lingpy profile -i forms.csv --cldf --clts --column=form --context -o ../etc/orthography.tsv
```

**Comment by LinguList** [comment]
And push it to the directory (PR not needed now). But maybe notify me if you do so.

**Comment by Wu-Urbanek** [comment]
KeyError: 'language_name'
is there any argument I can pass to lingpy api?

**Comment by LinguList** [comment]
```
$ git clone https://github.com/lingpy/lingpy.git
$ cd lingpy
$ python setup.py develop
```
Then try again. I fixed the bug yesterday, that's why you need to git-pull lingpy's most recent version...

**Comment by Wu-Urbanek** [comment]
ok. got the orthography file now. working on it

**Comment by LinguList** [comment]
You can first push it, okay? So we can see any changes you made on it afterwards.

For that, make a git checkout of the master:

```
git checkout master
```

then `git add` and `git commit` and `git push`, and then you can again branch to another branch, okay?

**Comment by Wu-Urbanek** [comment]
forgot to inform you, I pushed to the main branch

**Comment by Wu-Urbanek** [comment]
I just pushed the first version to etc

**Comment by Wu-Urbanek** [comment]
About the ə  in "rüzə" (wound). 
In Marrison's book, I think this word should be written as "rüza", the printing is not very clear here. 
STEDT's record is "rüzə". I check the raw data, ə only shows up once. 
Attachment is the screen-shot:
![rusa](https://user-images.githubusercontent.com/19792535/53355858-4d4fdd00-392a-11e9-9cfe-8b384991090c.png)
In Marrison's book, an "ə" should look like this :  
![schwa](https://user-images.githubusercontent.com/19792535/53356038-cbac7f00-392a-11e9-83d9-c488366fe92c.png)

So should I indicate this in the orthography file?

**Comment by tresoldi** [comment]
You could handle it in the profile by entering the entire word (with `^` and `$`), but this might be overusing the profile, as it is a correction of the data (and you should make sure that all `^rüzə` should be corrected as such, if there is more than one occurrence).

I'd say this is one of the few cases where it actually makes sense to use the exceptions in lexemes.

**Comment by Wu-Urbanek** [comment]
I just pushed a new version of orthography file, there is 18 BIPA error remaining.  
At least, *the strange alien question mark* does not exist in the  "form.csv" anymore.
I will keep trying tomorrow.

**Comment by Wu-Urbanek** [comment]
I just pushed a new version of orthography profile, a python script to make cldf and a new file "lexemes.csv".
Could you review the orthography profile?
