### ISSUE TITLE
once more: handling providors / contributors

### ISSUE THREAD

**Issue by LinguList** [lexibank/marrisonnaga#15]
We now added contributors to the dataset, but we cite STEDTT as source. So is STEDT now also a contributor, or just a source? Sorry for asking this repeatedly, but somehow it's still not clear how to best do it...

**Comment by xrotwang** [comment]
Either contributor or source, I would say. And last time the reasoning was
that the source is where stedt took it from and stedt's contribution is
mostly digitization.
The fact that we attribute stedt's contribution using a bibtex record
doesn't mean it's a source.

Johann-Mattis List <notifications@github.com> schrieb am Di., 26. Feb.
2019, 05:15:

**Comment by Wu-Urbanek** [comment]
I modified the contribution.md

**Comment by chrzyki** [comment]
So STEDT will be contributor everywhere for digitized data and the sources for the digitization will be our sources, correct?

**Comment by LinguList** [comment]
Yes, we should modify the sources also accordingly! I think it is okay enough to call STEDT "STEDT", and to list the url of the project in place of the githubname, right?

**Comment by xrotwang** [comment]
Adding `"url": "http://stedt.berkeley.edu/~stedt-cgi/rootcanal.pl/source/GEM-CNL"` now, ok?
