### ISSUE TITLE
Re-run and verify segmentation

### ISSUE THREAD

**Issue by chrzyki** [lexibank/marrisonnaga#16]
See again https://github.com/lexibank/pylexibank/commit/5bc70f4220c507ef75b5c7f5c9d1357b04ff5358, resulting in:

> Segments: 125 (0 BIPA errors, 0 CTLS sound class errors, 125 CLTS modified)
> Inventory size (avg): 40.70

versus the reported

> Segments: 126 (0 BIPA errors, 0 CTLS sound class errors, 126 CLTS modified)
> Inventory size (avg): 41.15

```
diff --git a/TRANSCRIPTION.md b/TRANSCRIPTION.md
index bcc6e32..42b93fe 100644
--- a/TRANSCRIPTION.md
+++ b/TRANSCRIPTION.md
@@ -10,7 +10,7 @@
 | i | 9142 | ✓ | ✓ |
 | u | 7416 | ✓ | ✓ |
 | e | 7200 | ✓ | ✓ |
-| + | 6755 | ✓ | ✓ |
+| + | 6790 | ✓ | ✓ |
 | o | 6677 | ✓ | ✓ |
 | k | 6558 | ✓ | ✓ |
 | g | 6499 | ✓ | ✓ |
@@ -66,7 +66,6 @@
 | kː | 41 | ✓ | ✓ |
 | īː | 36 | ✓ | ✓ |
 | ū | 36 | ✓ | ✓ |
-| _ | 35 | ✓ | ✓ |
 | rː | 34 | ✓ | ✓ |
 | ɲ | 30 | ✓ | ✓ |
 | bʰ | 26 | ✓ | ✓ |
@@ -132,7 +131,7 @@
 | ɣʷ | 1 | ✓ | ✓ |
 | ḁ | 1 | ✓ | ✓ |
```

**Comment by xrotwang** [comment]
all good now at 132 segments :)
