### ISSUE TITLE
add locations from Marrison

### ISSUE THREAD

**Issue by LinguList** [lexibank/marrisonnaga#18]
The locations are available in form of classical coordinates. As the glottocodes don't provide them always, they should be added separately. I The can be found in volume 2, page 377ff.

**Comment by LinguList** [comment]
If locations are missing, they can be left out.

**Comment by Wu-Urbanek** [comment]
Could you elaborate this task a bit more. In languages.csv, there are two columns "Latitude_in_source" and "Longitude_in_source". These are the geographic coordinates from the book. Should I add these two the column "Latitude" and "Longitude", or add the data in glottolog?

**Comment by LinguList** [comment]
sorry, did you already add the coordinates from the book there? If so, then this is excellent, I'll show you how to render them in lexibank when we meet!
