### ISSUE TITLE
add the original stedt data

### ISSUE THREAD

**Issue by LinguList** [lexibank/marrisonnaga#2]
the stedt data in their tsv-form should be added, so we can start processing

**Comment by LinguList** [comment]
also add them to the `raw/` folder.

**Comment by Wu-Urbanek** [comment]
I added Ao Chungli data today.

**Comment by LinguList** [comment]
we have to discuss this quickly tomorrow. So we have all data then in one place and can add this to the concepticon.

**Comment by Wu-Urbanek** [comment]
uploaded the raw file from http://stedt.berkeley.edu/~stedt-cgi/rootcanal.pl/source/GEM-CNL
