### ISSUE TITLE
How to cite the STEDT contribution?

### ISSUE THREAD

**Issue by LinguList** [lexibank/marrisonnaga#4]
Should we list STEDT as a source, as they digitized the datta, or rather as contributor? I'd say: contributor makes more sense. Role would be "digitization" or something? Any ideas  how we could best make this in a way that is consistent (this is not the first STEDT dataset we'll look into).

**Comment by xrotwang** [comment]
The [lexibank policies](https://github.com/lexibank/lexibank#attribution) say we should add STEDT as a contributor in `CONTRIBUTORS.md`, which I guess is ok? Maybe the contributors table could get a `source` column, which could then give the full citation? If consistency of this full citation is a concern, we could at some point replace the full citation with a citation key in a `lexibank` wide BibTeX reference file. Maybe we can do that right away, e.g. a file `references.bib` in https://github.com/lexibank/lexibank ?

**Comment by LinguList** [comment]
Yes, guess, this would be useful! @MacyL, you know the STEDT website, could you check quickly, where we have the naga-data, also for download, and what they ask to citte that as? Then, you make a bibtex-file out of that, with the STEDT key in there, and add it to https://github.com/lexibank/lexibank (ideally, with a pull request, so we can discuss the form)?

**Comment by xrotwang** [comment]
@MacyL please add the ref here: https://github.com/lexibank/lexibank/blob/master/references.bib

**Comment by Wu-Urbanek** [comment]
If the bibtex as follow is good? If it looks good to you then I will add it to reference.bib as soon as possible.

@PHDThesis{Marrison1967,
title={The classification of the Naga languages of north-east India.},
author={Marrison, Geoffrey Edward},
year={1967},
school={School of Oriental and African Studies (University of London)},
note={Accessed via STEDT database on 2018-05-01},
url = {http://stedt.berkeley.edu/~stedt-cgi/rootcanal.pl/source/GEM-CNL}
}

Should

**Comment by LinguList** [comment]
I'ts okay, but you could also treat it as the data by a provider:

```
@incollection{Marrison1967,
title = {The classification of the Naga languages of north-east India},
author = {Marrison, Geoffrey Edward},
year = {2015},
origyear = {1967},
collection = {STEDT database},
urldate = {2018-05-01},
editor = {Matisoff},
address = {Berkeley},
publisher = {Berkeley University}
}
```

And beware, Mei-Shin, that you had a final "." in your title. This is almost unforgivable. We need to be careful with references.

Or what would you think, @xrotwang? Is STEDT a collection in the bibtex sense, or do we just add the URL, and the note?

Or do we just quote STEDT as [Matisoff2015](http://bibliography.lingpy.org?key=Matisoff2015)?

**Comment by xrotwang** [comment]
I think I like the `incollection` version. This mimics what `clld` does for `Contribution`s in an aggregated database.

**Comment by LinguList** [comment]
Okay, this only has the little drawback of dating all datasets to 2015, but in this sense it is also correct: they were published with 2015 as STEDT datasets, and the "origyear" captures, when they were originally published.

**Comment by xrotwang** [comment]
we can also put this info - e.g. "originally published as ..." in a `howpublished` field.

**Comment by LinguList** [comment]
```
@incollection{Marrison1967,
title = {The classification of the Naga languages of north-east India},
author = {Marrison, Geoffrey Edward},
year = {2015},
origyear = {1967},
collection = {STEDT database},
urldate = {2018-05-01},
editor = {Matisoff, James},
address = {Berkeley},
publisher = {University of California},
url = {http://stedt.berkeley.edu/~stedt-cgi/rootcanal.pl/source/GEM-CNL}
}
```

This is cleaner now.

**Comment by xrotwang** [comment]
yes, looks good. And captures what's important, namely that we get the data from an already aggregated version - which is probably more relevant for judging the data.

**Comment by LinguList** [comment]
Yes, what I don't like about howpublished is that it's a free text field, where we don't have a very systematic way of coding things. The origyear etc., comes from bibtex and would be more explicit, similar to the "urldate". But for the time being, one could also use howpublished. And we could spare ourselves some work by allowing to add STEDT as cross-ref attribute.

**Comment by Wu-Urbanek** [comment]
I added it in references.bib 
Thank you all for the help.
