### ISSUE TITLE
concepts in csv form need to be escaped

### ISSUE THREAD

**Issue by LinguList** [lexibank/marrisonnaga#5]
@MacyL, your concepts.csv is corrupted, as you can see when checking github output. The reason is simple: csv requires that if a comma appears inside a cell, that the cell is placed in `"conten, conten"` this form. So please make sure that you check all concepts. Alternatively, we can just specify the list in concepticon.

**Comment by Wu-Urbanek** [comment]
updated :) 
There is one thing I need to check today, there should be 917 concepts, but I only have 911 concepts in the STEDT data.

**Comment by LinguList** [comment]
we'll check this, once we go for the lexibank-framework, where we convert data to csv...

**Comment by Wu-Urbanek** [comment]
The STEDT and the source both are having some issues : 
1. Glosses in STEDT data often have typo
2. There is a total of 909 concepts in STEDT raw data 
3. Only 911 glosses in the appendix in source but Marrison claims that his dataset includes 917 concepts.
4. STEDT includes some entries that's only mentioned in the source as examples, so there are not many words link to this gloss. 
------------------------------------------------------
My approach : 
1. Combine concepts in the STEDT data and the source (done)
2. Fix the typo if it's only one entry in the raw data (now) 
3. There are about 20 concepts that's not listed in the STEDT data but I can find the words in the appendix. I will add them into the raw data. (today)

**Comment by LinguList** [comment]
No!

**Comment by LinguList** [comment]
You are not allowed to fix typos inteh STEDT data!

**Comment by LinguList** [comment]
This is against our principles in lexibank. 

Instead, what you do is: add a row in the concepts.csv, where you specify the correct concepticon ID, or you add another column to the concepticon.csv: `Concept_in_STEDT`, so we can trace both of them. 

No changes to the raw data are accepted, it has to be done by our data in `etc/`

**Comment by Wu-Urbanek** [comment]
what about the concepts that's documented in the resource but not in the STEDT data? another file or we ignore them?

**Comment by LinguList** [comment]
If we don't have data for them, we can't include them. That's what it is. So they will be ignore already by the code. Unless you re-type off the whole book and offer it in some format, we stick with stedt and use what they give to us.

**Comment by LinguList** [comment]
What you need to understand, @MacyL, is that we have some fundamental design principles in `lexibank` which are important to be faithful to sources, and those state that we do not cherry-pick data and do things in a transparent way. If you modify the source now, the source is no longer the same as offered by STEDT, so we can't trace it back. Instead, we modify obvious errors in stedt with our code (and the csv-files we have). So we correct the data in a transparent way, without modifying the original data (which is STEDT in this case).

**Comment by Wu-Urbanek** [comment]
We have three columns already : ENGLISH , ENGLISH_in_STEDT, ENGLISH_in_source.  I document in a notes.md file. 
I have those concepts in the resource, I previous typed down in case we need them in the future. Those concepts are mapped with concepticon, but people won't find the corresponding words in csv data.

**Comment by LinguList** [comment]
Okay, notes.md needs to be NOTES.md. I'd also ask you to submit all data you have NOW, and then switch to another branch in git. So you can make a formal pull request afterwards, okay?

As to the three columns, this is allright! We'll use the code to then select the right one and to convert to a good human-readable English concept.

**Comment by LinguList** [comment]
for branching (having committed all you done currently):
```
$ git branch updating
$ git checkout updating
```

Later, git-push this as well, and then you can make a PR later.
