### ISSUE TITLE
How do we handle notes on the dataset?

### ISSUE THREAD

**Issue by LinguList** [lexibank/marrisonnaga#6]
This question was often addressed, but never sufficiently handled. I think this dataset is a good example:

- @MacyL corrected entries from the provider, STEDT and also segmented data by hand
- glottocodes are accompanied by locations, which I assume, @MacyL looked up as well

So it would be good, if we could have a notes.md, where we could write some text, which -- ideally -- would be parsed into Zenodo, right? @xrotwang, is that possible, or do we have a file from Zenodo where we should do that?

In any case, this dataset is in quite some good state now: concepts are linked to concepticon, and if I understand this correctly, @MacyL (but please confirm) hand-corrected data by comparing with the original source.

**Comment by Wu-Urbanek** [comment]
I looked up the STEDT words and then checked each word with the original thesis. STEDT tends to write nasalized n in the form of "ny", so I spent extra time on checking diacritics (I will confirm this case with Yunfan tomorrow).
I currently test how much time it will take to type down some words, so I set up a raw.ods today. I will delete this file tomorrow and use computational approach: download data and curate the lexicon by checking the original data.

**Comment by xrotwang** [comment]
We do recognize a [NOTES.md](https://github.com/lexibank/bantubvd/blob/master/NOTES.md) file, which currently is included in the auto-generated `README.md`. We could also add this to `.zenodo.json`, I guess.

**Comment by LinguList** [comment]
Okay, we will use this as a first test / example for a notes.md, when finalizing the data.

**Comment by xrotwang** [comment]
@LinguList it's `NOTES.md`. Lowercase won't work.

**Comment by LinguList** [comment]
Yes, was in fact clear to me, was just too lazy to press the caps button... :)
